version: "3"
services:
  php:
    build: './php/'
    container_name: PHPcontainer44
    networks:
      - backend
    volumes:
      - './public_html:/var/www/html'
  apache:
    build: './apache/'
    container_name: Apachecontainer44
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "81:80"
    volumes:
      - './public_html:/var/www/html'
networks:
  frontend:
  backend: